Create Database Customers

Use Customers

Select * from Fact

select * from Product

Select * from Location

/*1. Display the number of states present in the LocationTable.*/

Select Count(Distinct State) as count_of_States from Location

/*2. How many products are of regular type?*/

Select Count(Product) as Count_of_Regular_Product from Product where type = 'Regular'

/*3. How much spending has been done on marketing of product ID 1?*/

select SUM(Marketing) as Total_Marketing_Expenses from Fact where ProductId = 1

/*4. What is the minimum sales of a product?*/

Select MIN(Sales) as Min_sale from Fact

Select ProductId, MIN(Sales) as Min_Sale from Fact Group by ProductId Order by ProductId

/*5. Display the max Cost of Good Sold (COGS).*/

Select MAX(COGS) as Max_COGS from Fact

Select ProductId, MAX(COGS) as MAX_COGS from FACT Group by ProductId order by ProductId

/*6. Display the details of the product where product type is coffee.*/

Select * from Product where Product_type = 'Coffee'

/*7. Display the details where total expenses are greater than 40.*/

Select * from Fact where Total_Expenses > 40

/*8. What is the average sales in area code 719?*/

Select AVG(Sales) as Avg_Sales from Fact where Area_code = 719

Select ProductID, AVG(Sales) As Avg_sales from Fact where Area_code = 719 Group by ProductId order by ProductId

/*9. Find out the total profit generated by Colorado state.*/

Select Sum(F.Profit) as Total_Profit from Fact F Join Location L
on F.Area_code = L.Area_code where L.State = 'Colorado'

Select F.ProductId, Sum(F.Profit) as Total_Profit from Fact F Join Location L
on F.Area_code = L.Area_code where L.State = 'Colorado' Group by ProductId order by ProductId

/*10. Display the average inventory for each product ID.*/

Select ProductId, Avg(Inventory) as Avg_Inventory from Fact Group by ProductId order by ProductId

/*11. Display state in a sequential order in a Location Table.*/

Select Distinct state from Location Order by state

/*12. Display the average budget of the Product where the average budget
margin should be greater than 100.*/

Select ProductId, Avg(Budget_Margin) as Avg_Budget_Margin from Fact Group by ProductId Having Avg(Budget_Margin) > 100 Order by ProductId

/*13. What is the total sales done on date 2010-01-01?*/

Select Date, Sum(Sales) as Total_Sales from Fact where date = '2010-01-01' Group by Date


/*14. Display the average total expense of each product ID on an individual date.*/

Select ProductId, Date, Avg(Total_Expenses) as Avg_total_Expenses from Fact Group by ProductId, Date Order by ProductId, Date

/*15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.*/

Select F.Date, F.ProductId, P.Product_type, P.Product, F.Sales, F.Profit, L.State, L.Area_code From Fact F 
Inner Join Product P on F.ProductId = P.ProductId Inner Join Location L on F.Area_code = L.Area_Code

/*16. Display the rank without any gap to show the sales wise rank.*/

Select *, dense_rank() over(order by Sales desc) as Sales_Rank from Fact

/*17. Find the state wise profit and sales.*/

Select L.State, Sum(F.Profit) as Total_profit, Sum(F.Sales) as Total_Sales from Fact F Inner Join Location L
on F.Area_code = L.Area_code Group by State

/*18. Find the state wise profit and sales along with the productname.*/ 

Select L.State, P.Product, Sum(F.Profit) as Total_profit, Sum(F.Sales) as Total_Sales from Fact F Inner Join Location L
on F.Area_code = L.Area_code Inner Join Product P on F.ProductId = P.ProductId Group by State,Product

/*19. If there is an increase in sales of 5%, calculate the increasedsales.*/

Select ProductId, Sales as Old_Sales, (Sales*1.05) as Increase_Sales from Fact

/*20. Find the maximum profit along with the product ID and producttype.*/

Select F.ProductId, P.Product_Type, Max(F.Profit) as Max_Profit from Fact F Inner Join Product P
on F.ProductId = P.ProductId Group by P.Product_Type, F.ProductId 

/*21. Create a stored procedure to fetch the result according to the product typefrom Product Table.*/

Create Procedure SP_Product
as
Select * from Product Order by Product_Type

Exec SP_Product

/*22. Write a query by creating a condition in which if the total expenses is lessthan60 then it is a profit or else loss.*/

Select *, IIF ( Total_Expenses < 60, 'Profit', 'Loss') as Profit_Or_Loss from Fact

/*23. Give the total weekly sales value with the date and product ID details. Useroll-up to pull the data in hierarchical order.*/

SELECT DATEPART(WEEK, Date) AS Week, ProductId, SUM(Sales) AS Total_weekly_sale FROM Fact
GROUP BY ROLLUP(DATEPART(WEEK, Date), ProductId);

/*24. Apply union and intersection operator on the tables which consist of
attribute area code.*/

Select Area_code from Fact
Union
Select Area_code from Location

Select Area_code from Fact
Intersect
Select Area_code from Location

/*25. Create a user-defined function for the product table to fetch a particular
product type based upon the user’s preference. */

CREATE FUNCTION Get_Product
(@ProductType VARCHAR(50))
RETURNS TABLE
AS
RETURN
(SELECT * FROM Product WHERE Product_Type = @ProductType)

SELECT * FROM dbo.Get_Product('Espresso')

/*26. Change the product type from coffee to tea where productID is 1 and undo it. */

BEGIN TRANSACTION

UPDATE Product
SET Product_Type = 'tea'
WHERE productID = 1

ROLLBACK

select * from Product

/*27. Display the date, product ID and sales where total expenses are
between 100 to 200.*/ 

Select Date, ProductId, Sales, Total_expenses from Fact where Total_Expenses between 100 and 200 order by Total_Expenses

/*28. Delete the records in the Product Table for regular type.*/ 

Delete from Product where Type = 'Regular'


/*29. Display the ASCII value of the fifth character from the column Product.*/

SELECT Product, ASCII(SUBSTRING(Product, 5, 1)) AS ASCII_value_of_the_fifth_character
FROM Product
WHERE Product = 'Mint'